//
//  EKPConstants.h
//  Edukonnect-Pro
//
//  Created by Dinesh Panwar on 30/09/14.
//  Copyright (c) 2014 Kedar Desai. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface EKPConstants : NSObject

FOUNDATION_EXPORT NSString *const REGISTRATION_SCREEN_TITLE;
FOUNDATION_EXPORT NSString *const LOGIN_SCREEN_TITLE;
FOUNDATION_EXPORT NSString *const DASHBOARD_SCREEN_TITLE;

FOUNDATION_EXPORT NSString *const REGISTRATION_SECCESSFUL;

FOUNDATION_EXPORT NSString *const EKP_THEME;
FOUNDATION_EXPORT NSString *const EKP_USER;
FOUNDATION_EXPORT NSString *const EKP_CURRENT_STUDENT;
FOUNDATION_EXPORT NSString *const EKP_STUDENT_LIST;

FOUNDATION_EXPORT NSString *const BASE_API_URL;
FOUNDATION_EXPORT NSString *const REGISTRATION_API_URL;
FOUNDATION_EXPORT NSString *const LOGIN_API_URL;
FOUNDATION_EXPORT NSString *const EDIT_PROFILE_API_URL;
FOUNDATION_EXPORT NSString *const NOTICEBOARD_API_URL;
FOUNDATION_EXPORT NSString *const NOTICE_API_URL;
FOUNDATION_EXPORT NSString *const EVENT_API_URL;
FOUNDATION_EXPORT NSString *const RESULT_API_URL;
FOUNDATION_EXPORT NSString *const TIMETABLE_API_URL;
FOUNDATION_EXPORT NSString *const GALLARY_API_URL;
FOUNDATION_EXPORT NSString *const GALLARY_IMAGE_API_URL;

FOUNDATION_EXPORT NSString *const LOGIN_API_SCHOOL_DETAILS;
FOUNDATION_EXPORT NSString *const LOGIN_API_SCHOOL_ADDRESS;
FOUNDATION_EXPORT NSString *const LOGIN_API_SCHOOL_EMAIL;
FOUNDATION_EXPORT NSString *const LOGIN_API_SCHOOL_LOGO;
FOUNDATION_EXPORT NSString *const LOGIN_API_SCHOOL_NAME;
FOUNDATION_EXPORT NSString *const LOGIN_API_STUDENT_DETAILS;
FOUNDATION_EXPORT NSString *const LOGIN_API_STUDENT_ADDRESS;
FOUNDATION_EXPORT NSString *const LOGIN_API_STUDENT_BIRTHDAY;
FOUNDATION_EXPORT NSString *const LOGIN_API_STUDENT_CLASS;
FOUNDATION_EXPORT NSString *const LOGIN_API_STUDENT_GRNO;
FOUNDATION_EXPORT NSString *const LOGIN_API_STUDENT_NAME;
FOUNDATION_EXPORT NSString *const LOGIN_API_STUDENT_ROLLNO;
FOUNDATION_EXPORT NSString *const LOGIN_API_STUDENT_SEX;

FOUNDATION_EXPORT NSString *const STATUS_KEY;
FOUNDATION_EXPORT NSString *const MESSAGE_KEY;


@end
